using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text.Json;

public static class AdvancedReportTests {
 public static void Run() {
  void Check(bool value,string message){if(!value)throw new Exception(message);}
  var day=new DateTime(2026,10,5);var data=new ReportSnapshot {From=day,Through=day.AddDays(30),Users=new List<ReportUser>{new ReportUser {Id=1,Name="A,\"one\""},new ReportUser {Id=2,Name="=excluded"},new ReportUser {Id=3,Name="Zero"}},Records=new List<ReportRecord>{new ReportRecord {Id=1,UserId=1,ProjectId=11,Project="Project A",ActivityId=21,Activity="Design",Begin=day.AddHours(9),End=day.AddHours(10.5),Seconds=5400},new ReportRecord {Id=2,UserId=1,ProjectId=11,Project="Project A",ActivityId=21,Activity="Design",Begin=day.AddDays(1).AddHours(9),End=day.AddDays(1).AddHours(10),Seconds=3600},new ReportRecord {Id=3,UserId=2,ProjectId=11,Project="Project A",ActivityId=21,Activity="Design",Begin=day.AddHours(11),End=day.AddHours(12),Seconds=3600},new ReportRecord {Id=4,UserId=1,ProjectId=12,Project="Project B",ActivityId=22,Activity="Review",Begin=day.AddDays(2).AddHours(9),End=day.AddDays(2).AddHours(11),Seconds=7200},new ReportRecord {Id=5,UserId=1,ProjectId=11,Project="Project A",ActivityId=21,Activity="Design",Begin=day.AddHours(14),End=null,Seconds=null}}};
  var filtered=AdvancedReportTables.Exclude(data,new[]{2});Check(filtered.Users.Count==2&&filtered.Records.Count==4,"Excluded user leaked into reports");
  var daily=AdvancedReportTables.Daily(filtered,day,day.AddDays(6));Check(daily.Columns.Count==9&&(decimal)daily.Rows[0][1]==1.5m&&(decimal)daily.Rows[0]["合計(h)"]==4.5m&&(decimal)daily.Rows[1][1]==0,"Daily matrix totals/zero users");
  var details=AdvancedReportTables.ProjectDetails(filtered,new HashSet<int>{11});Check(details.Rows.Count==3&&(decimal)details.Rows[0]["作業時間(h)"]==1.5m&&(decimal)details.Rows[0]["作業時間(分)"]==90&&details.Rows.Cast<DataRow>().Count(r=>r.IsNull("作業時間(h)"))==1,"Project details duration/running filter");
  var config=new PeriodReportConfig {ServerUrl="https://example.test/kimai",Rows=new List<ProjectPeriodSpec>{new ProjectPeriodSpec {ProjectId=11,ProjectName="Project A",Header="第1期間",From=day,Through=day},new ProjectPeriodSpec {ProjectId=11,ProjectName="Project A",Header="第2期間",From=day.AddDays(1),Through=day.AddDays(1)},new ProjectPeriodSpec {ProjectId=12,ProjectName="Project B",Header="第1期間",From=day.AddDays(2),Through=day.AddDays(2)}}};
  var restored=PeriodReportConfig.Read(JsonSerializer.Serialize(config));Check(restored.Rows.Count==3&&restored.Rows[2].From==day.AddDays(2)&&restored.ServerUrl==config.ServerUrl,"Period config round trip");
  var periods=AdvancedReportTables.Periods(filtered,restored,new[]{(11,21,"Design"),(11,23,"Unused"),(12,22,"Review")});Check(periods.Columns[2].Caption=="第1期間 (h)"&&periods.Rows.Count==5,"Period headers or zero activities missing");var a=periods.Rows.Cast<DataRow>().Single(r=>(string)r[0]=="Project A"&&(string)r[1]=="Design");Check((decimal)a[2]==1.5m&&(decimal)a[3]==1m&&(decimal)a[4]==2.5m,"Independent date ranges aggregated incorrectly");var b=periods.Rows.Cast<DataRow>().Single(r=>(string)r[0]=="Project B"&&(string)r[1]=="Review");Check((decimal)b[2]==2m&&b.IsNull(3),"Project-specific dates or undefined period");
  restored.Rows[1].From=day;var overlap=AdvancedReportTables.Periods(filtered,restored);Check((decimal)overlap.Rows[0][3]==2.5m,"Overlapping periods must be independent");
  var open=PeriodReportConfig.Read(JsonSerializer.Serialize(config));open.Rows[0].From=null;open.Rows[1].Through=null;var openTable=AdvancedReportTables.Periods(filtered,open);var summary=AdvancedReportTables.PeriodSummary(openTable);Check(summary.Rows.Count==2&&(decimal)summary.Rows[0][1]==1.5m&&(decimal)summary.Rows[0][2]==1m,"Open-ended range summary incorrect");open.Rows[0].Through=null;Check((decimal)AdvancedReportTables.PeriodSummary(AdvancedReportTables.Periods(filtered,open)).Rows[0][1]==2.5m,"All-time range incorrect");
  bool rejected=false;restored.Rows.Add(restored.Rows[0]);try{restored.Validate();}catch(ArgumentException){rejected=true;}Check(rejected,"Duplicate project/header accepted");
  var csv=AdvancedReportTables.Csv(details);Check(csv.Contains("\"A,\"\"one\"\"\"")&&csv.Contains("1.5,90"),"CSV escaping/numeric precision");var malicious=new DataTable("csv");malicious.Columns.Add("text");malicious.Rows.Add("=1+1\nnext");Check(AdvancedReportTables.Csv(malicious).Contains("\"'=1+1\nnext\""),"CSV formula/newline escaping");details.DefaultView.RowFilter="[アクティビティ名] = 'missing'";Check(AdvancedReportTables.Csv(details).Split('\n',StringSplitOptions.RemoveEmptyEntries).Length==1,"CSV ignores active filter");
  Console.WriteLine("PASS: user exclusions, daily matrix, project details, period boundaries/overlap/zero rows, config import-export and CSV.");
 }
}
