<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>2026.10.9.0231</Version>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>KimaiBlocks</AssemblyName>
    <StartupObject>Blocks</StartupObject>
    <ApplicationIcon>Assets/KimaiBlocks.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Update="defaults.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="settings.override.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="settings.policy.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Resource Include="Assets/KimaiBlocks.ico" />
    <PackageReference Include="MarkZither.KimaiDotNet.ApiClient" Version="1.0.0" />
  </ItemGroup>
</Project>











