using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using Microsoft.Win32;

public partial class Blocks {
 void ShowPeriodReports(Window owner) {
  if(service==null)return;var api=service;
  var w=new Window {Title="プロジェクト別・複数期間の集計",Owner=owner,Width=1200,Height=850,MinWidth=880,MinHeight=600,WindowStartupLocation=WindowStartupLocation.CenterOwner};var root=new DockPanel {Margin=new Thickness(16)};w.Content=root;
  var top=new StackPanel();DockPanel.SetDock(top,Dock.Top);root.Children.Add(top);var help=Label("縦がプロジェクト、横が期間名です。交点を選び、上の欄で期間を設定します。期間名は変更できます。\n各期間を独立して集計します。期間が重複した実績はそれぞれの列に含まれ、合計は期間列の和です。",12);help.TextWrapping=TextWrapping.Wrap;top.Children.Add(help);
  var persisted=settings.PeriodReport;bool sameServer=string.IsNullOrWhiteSpace(persisted.ServerUrl)||persisted.ServerUrl==api.BaseUrl;
  var rows=new ObservableCollection<ProjectPeriodSpec>(sameServer?PeriodReportConfig.Read(JsonSerializer.Serialize(persisted)).Rows:new List<ProjectPeriodSpec>());
  var editor=new WrapPanel();top.Children.Add(editor);
  var names=api.Projects.Where(p=>p.Visible!=false).Select(p=>api.ProjectName(p.Id.Value)).ToArray();var project=new ProjectSearchBox(names,names.FirstOrDefault(),Matches) {Width=280,Margin=new Thickness(4)};var header=new ComboBox {IsEditable=true,IsTextSearchEnabled=false,Text="第1期間",Width=150,Margin=new Thickness(4),Padding=new Thickness(5)};var from=new DatePicker {SelectedDate=Monday(DateTime.Today),Width=135,Margin=new Thickness(4)};var through=new DatePicker {SelectedDate=Monday(DateTime.Today).AddDays(6),Width=135,Margin=new Thickness(4)};
  CheckBox noStart=new CheckBox {Content="開始からすべて",Margin=new Thickness(4)},noEnd=new CheckBox {Content="以降すべて",Margin=new Thickness(4)};noStart.Checked+=(s,e)=>from.IsEnabled=false;noStart.Unchecked+=(s,e)=>from.IsEnabled=true;noEnd.Checked+=(s,e)=>through.IsEnabled=false;noEnd.Unchecked+=(s,e)=>through.IsEnabled=true;
  editor.Children.Add(Label("プロジェクト",12));editor.Children.Add(project);editor.Children.Add(Label("列名",12));editor.Children.Add(header);editor.Children.Add(noStart);editor.Children.Add(from);editor.Children.Add(through);editor.Children.Add(noEnd);
  var rowActions=new WrapPanel();top.Children.Add(rowActions);var table=new DataGrid {Height=200,IsReadOnly=true,AutoGenerateColumns=false,CanUserAddRows=false,CanUserDeleteRows=false,CanUserReorderColumns=false,SelectionUnit=DataGridSelectionUnit.Cell,SelectionMode=DataGridSelectionMode.Single,FrozenColumnCount=1,Margin=new Thickness(4)};top.Children.Add(table);
  var matrixProjects=new List<int>();var matrixHeaders=new List<string>();ProjectPeriodSpec selectedSpec=null;bool rebuilding=false;
  void Matrix(){rebuilding=true;try{var data=new DataTable();data.Columns.Add("Project");matrixProjects=rows.Select(r=>r.ProjectId).Distinct().ToList();matrixHeaders=rows.Select(r=>r.Header.Trim()).Distinct().ToList();foreach(var name in matrixHeaders)data.Columns.Add("P"+data.Columns.Count);data.Columns.Add("ProjectId",typeof(int));foreach(int id in matrixProjects){var row=data.NewRow();row["ProjectId"]=id;row[0]=api.ProjectName(id);for(int i=0;i<matrixHeaders.Count;i++){var spec=rows.FirstOrDefault(r=>r.ProjectId==id&&r.Header.Trim()==matrixHeaders[i]);row[i+1]=spec==null?"未設定":(spec.From?.ToString("yyyy/MM/dd")??"開始から")+" ～ "+(spec.Through?.ToString("yyyy/MM/dd")??"以降すべて");}data.Rows.Add(row);}table.Columns.Clear();table.Columns.Add(new DataGridTextColumn {Header="プロジェクト",SortMemberPath="Project",Binding=new Binding("[Project]"),Width=230});for(int i=0;i<matrixHeaders.Count;i++)table.Columns.Add(new DataGridTextColumn {Header=matrixHeaders[i],SortMemberPath="P"+(i+1),Binding=new Binding("[P"+(i+1)+"]"),Width=240});table.ItemsSource=data.DefaultView;string entered=header.Text;header.ItemsSource=matrixHeaders.ToArray();header.Text=entered;}finally{rebuilding=false;}}
  void SelectSpec(ProjectPeriodSpec row){selectedSpec=row;if(row==null)return;project.SelectedItem=row.ProjectName;header.Text=row.Header;noStart.IsChecked=!row.From.HasValue;noEnd.IsChecked=!row.Through.HasValue;from.SelectedDate=row.From;through.SelectedDate=row.Through;}
  table.SelectedCellsChanged+=(s,e)=>{if(rebuilding||table.SelectedCells.Count==0)return;var cell=table.SelectedCells[0];if(cell.Item is not DataRowView view||cell.Column==null||!table.Columns.Contains(cell.Column)||view.Row.RowState==DataRowState.Detached||!view.Row.Table.Columns.Contains("ProjectId"))return;string field=cell.Column.SortMemberPath;if(field==null||!field.StartsWith("P")||!int.TryParse(field.Substring(1),out int period)||period<1||period>matrixHeaders.Count)return;int id=(int)view.Row["ProjectId"];string name=matrixHeaders[period-1];var spec=rows.FirstOrDefault(r=>r.ProjectId==id&&r.Header.Trim()==name);SelectSpec(spec);project.SelectedItem=api.ProjectName(id);header.Text=name;};
  var actions=new WrapPanel();top.Children.Add(actions);var message=Label(sameServer?"設定は保存して次回も利用できます。集計前に保存されます。":"保存済み設定は別サーバー用です。この接続先のプロジェクトを選択してください。",12);message.TextWrapping=TextWrapping.Wrap;top.Children.Add(message);
  var result=new ContentControl {Margin=new Thickness(4)};root.Children.Add(result);DataTable output=null;ReportSnapshot snapshot=null;HashSet<int> selectedUsers=null;CancellationTokenSource cancellation=null;bool loading=false,closeAfter=false,discard=false;Button cancel=null;
  PeriodReportConfig Config(){var config=new PeriodReportConfig {ServerUrl=api.BaseUrl,Rows=rows.ToList()};config.Validate();foreach(var row in config.Rows){var p=api.Projects.FirstOrDefault(p=>p.Id==row.ProjectId&&p.Visible!=false);if(p==null)throw new ArgumentException("利用できないプロジェクトがあります。該当行を削除または変更してください。ID: "+row.ProjectId);row.ProjectName=api.ProjectName(row.ProjectId);}return config;}
  bool Save(){try{if(Locked("PeriodReport.Rows"))return true;var config=Config();var previous=settings.PeriodReport;settings.PeriodReport=PeriodReportConfig.Read(JsonSerializer.Serialize(config));try{StoreSettings(false);}catch{settings.PeriodReport=previous;throw;}message.Text="期間設定を保存しました。";return true;}catch(Exception ex){MessageBox.Show(w,ReportSettingsError(ex),"期間設定を保存できません");return false;}}
  void UpdateRow(bool replace){try{if(project.SelectedItem is not string name||noStart.IsChecked!=true&&!from.SelectedDate.HasValue||noEnd.IsChecked!=true&&!through.SelectedDate.HasValue)throw new ArgumentException("プロジェクト・開始日・終了日を選択してください。");var p=api.Projects.FirstOrDefault(p=>api.ProjectName(p.Id.Value)==name);var item=new ProjectPeriodSpec {ProjectId=p.Id.Value,ProjectName=name,Header=header.Text.Trim(),From=noStart.IsChecked==true?null:from.SelectedDate?.Date,Through=noEnd.IsChecked==true?null:through.SelectedDate?.Date};var test=new PeriodReportConfig {Rows=rows.Where(r=>!replace||r!=selectedSpec).Concat(new[]{item}).ToList()};test.Validate();if(replace){if(selectedSpec is not ProjectPeriodSpec old)throw new ArgumentException("更新する行を選択してください。");rows[rows.IndexOf(old)]=item;}else rows.Add(item);SelectSpec(item);Matrix();output=null;result.Content=null;message.Text="設定を変更しました。再集計してください。";}catch(Exception ex){MessageBox.Show(w,SafeError(ex),"期間の入力確認");}}
  rowActions.Children.Add(ButtonOf("交点を追加",()=>UpdateRow(false)));rowActions.Children.Add(ButtonOf("選択期間を更新",()=>UpdateRow(true)));rowActions.Children.Add(ButtonOf("選択期間を削除",()=>{if(selectedSpec is ProjectPeriodSpec row){rows.Remove(row);selectedSpec=null;Matrix();output=null;result.Content=null;}}));rowActions.Children.Add(ButtonOf("設定を保存",()=>Save()));
  rowActions.Children.Add(ButtonOf("期間名を変更",()=>{try{if(selectedSpec==null)throw new ArgumentException("変更する列の設定済みセルを選択してください。");string old=selectedSpec.Header.Trim(),name=header.Text.Trim();if(string.IsNullOrWhiteSpace(name)||name.Length>80||rows.Any(r=>r.Header.Trim()==name&&r.Header.Trim()!=old))throw new ArgumentException("重複しない期間名を80文字以内で指定してください。");foreach(var row in rows.Where(r=>r.Header.Trim()==old))row.Header=name;Matrix();output=null;result.Content=null;}catch(Exception ex){MessageBox.Show(w,ReportSettingsError(ex),"期間名の確認");}}));
  var import=ButtonOf("設定をインポート…",()=>{var dialog=new OpenFileDialog {Filter="期間設定 (*.json)|*.json"};if(dialog.ShowDialog(w)!=true)return;try{var config=PeriodReportConfig.Read(File.ReadAllText(dialog.FileName));if(!string.IsNullOrWhiteSpace(config.ServerUrl)&&config.ServerUrl!=api.BaseUrl)throw new ArgumentException("別サーバーの設定です。接続先の一致する設定を選んでください。");foreach(var row in config.Rows){if(!api.Projects.Any(p=>p.Id==row.ProjectId&&p.Visible!=false))throw new ArgumentException("利用できないプロジェクトID: "+row.ProjectId);row.ProjectName=api.ProjectName(row.ProjectId);}rows.Clear();foreach(var row in config.Rows)rows.Add(row);Matrix();SelectSpec(rows.FirstOrDefault());output=null;result.Content=null;Save();}catch(Exception ex){MessageBox.Show(w,SafeError(ex),"インポートできません");}});actions.Children.Add(import);
  actions.Children.Add(ButtonOf("設定をエクスポート…",()=>{try{var config=Config();var dialog=new SaveFileDialog {Filter="期間設定 (*.json)|*.json",FileName="project-periods.json"};if(dialog.ShowDialog(w)==true)File.WriteAllText(dialog.FileName,JsonSerializer.Serialize(config,SettingsLayers.Options),new UTF8Encoding(false));}catch(Exception ex){MessageBox.Show(w,SafeError(ex),"エクスポートできません");}}));
  async Task Display(PeriodReportConfig config){if(config.Rows.Any(r=>snapshot.From.HasValue&&(!r.From.HasValue||r.From.Value.Date<snapshot.From.Value.Date)||snapshot.Through.HasValue&&(!r.Through.HasValue||r.Through.Value.Date>snapshot.Through.Value.Date)))throw new ArgumentException("設定期間が取得済み範囲を超えています。取得して集計を実行してください。");var data=MemberReports.Filter(AdvancedReportTables.Exclude(snapshot,settings.ExcludedReportUserIds),selectedUsers);var activities=config.Rows.Select(r=>r.ProjectId).Distinct().SelectMany(id=>api.ForProject(id).Select(a=>(id,a.Id.Value,api.ActivityName(a.Id.Value)))).ToList();var detail=await Task.Run(()=>AdvancedReportTables.Periods(data,config,activities,cancellation?.Token??CancellationToken.None));var summary=AdvancedReportTables.PeriodSummary(detail);output=summary;var tabs=new TabControl();tabs.Items.Add(new TabItem {Header="プロジェクト × 期間",Content=ReportGrid(summary),Tag=summary});tabs.Items.Add(new TabItem {Header="アクティビティ別",Content=ReportGrid(detail),Tag=detail});tabs.SelectionChanged+=(s,e)=>{if(e.Source==tabs&&tabs.SelectedItem is TabItem tab)output=(DataTable)tab.Tag;};tabs.SelectedIndex=0;result.Content=tabs;message.Text="集計済み · "+data.Records.Count+"件（取得範囲内） · "+data.Users.Count+"人 · "+data.Timezone+"\n計測中・時間不明は時間合計から除外。開始日基準。";}
  var members=ButtonOf("対象ユーザー…",async()=>{if(snapshot!=null&&ChooseMembers(w,AdvancedReportTables.Exclude(snapshot,settings.ExcludedReportUserIds).Users,selectedUsers,out var chosen)){selectedUsers=chosen;loading=true;editor.IsEnabled=rowActions.IsEnabled=actions.IsEnabled=table.IsEnabled=false;cancel.IsEnabled=true;cancellation=new CancellationTokenSource();output=null;result.Content=null;try{await Display(Config());}catch(OperationCanceledException){message.Text="集計をキャンセルしました。";}catch(Exception ex){MessageBox.Show(w,SafeError(ex),"再集計できません");}finally{loading=false;editor.IsEnabled=rowActions.IsEnabled=actions.IsEnabled=table.IsEnabled=true;LockSetting(editor,"PeriodReport.Rows");LockSetting(rowActions,"PeriodReport.Rows");cancel.IsEnabled=false;cancellation.Dispose();cancellation=null;if(closeAfter)w.Close();}}});members.IsEnabled=false;actions.Children.Add(members);
  var fetch=ButtonOf("取得して集計",async()=>{PeriodReportConfig config;try{config=Config();if(config.Rows.Count==0)throw new ArgumentException("期間を1行以上追加してください。");if(!Save())return;}catch(Exception ex){MessageBox.Show(w,SafeError(ex),"設定確認");return;}loading=true;editor.IsEnabled=rowActions.IsEnabled=actions.IsEnabled=table.IsEnabled=false;cancel.IsEnabled=true;cancellation=new CancellationTokenSource();output=null;result.Content=null;snapshot=null;members.IsEnabled=false;try{snapshot=await api.ReadReportAsync(config.Rows.Any(r=>!r.From.HasValue)?null:config.Rows.Min(r=>r.From),config.Rows.Any(r=>!r.Through.HasValue)?null:config.Rows.Max(r=>r.Through),new Progress<string>(text=>{if(loading&&output==null)message.Text=text;}),cancellation.Token);message.Text="集計表を作成しています…";await Display(config);members.IsEnabled=true;}catch(OperationCanceledException){message.Text="取得をキャンセルしました。";}catch(Exception ex){message.Text="取得に失敗しました。";MessageBox.Show(w,SafeError(ex),"複数期間集計の取得失敗");}finally{loading=false;editor.IsEnabled=rowActions.IsEnabled=actions.IsEnabled=table.IsEnabled=true;LockSetting(editor,"PeriodReport.Rows");LockSetting(rowActions,"PeriodReport.Rows");cancel.IsEnabled=false;cancellation.Dispose();cancellation=null;if(closeAfter)w.Close();}});
  actions.Children.Add(fetch);actions.Children.Add(ButtonOf("CSV出力…",()=>ExportReportCsv(w,output)));
  var bottom=new WrapPanel();DockPanel.SetDock(bottom,Dock.Bottom);root.Children.Remove(result);root.Children.Add(bottom);root.Children.Add(result);cancel=ButtonOf("取得をキャンセル",()=>cancellation?.Cancel());cancel.IsEnabled=false;bottom.Children.Add(cancel);bottom.Children.Add(ButtonOf("閉じる",()=>w.Close()));bottom.Children.Add(ButtonOf("保存せず閉じる",()=>{discard=true;w.Close();}));
  Matrix();SelectSpec(rows.FirstOrDefault());LockSetting(editor,"PeriodReport.Rows");LockSetting(rowActions,"PeriodReport.Rows");LockSetting(import,"PeriodReport.Rows");
  w.Closing+=(s,e)=>{if(loading){e.Cancel=true;closeAfter=true;cancellation?.Cancel();}else if(!discard&&(sameServer||rows.Count>0)&&!Save())e.Cancel=true;};w.ShowDialog();
 }
}
