using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using MarkZither.KimaiDotNet.Models;

public partial class Blocks {
 static async Task RunRevisionUiChecks(string folder) {
  Projects=new[]{"A","B","C","D"};var w=new Blocks(true);w.file=Path.Combine(folder,"revision-cache.json");w.testSettingsPath=Path.Combine(folder,"revision-settings.json");w.state=new State();w.Show();
  try {
   void Check(bool condition,string message){if(!condition)throw new Exception(message);}
   var setup=Path.Combine(folder,"configuration");Directory.CreateDirectory(setup);File.WriteAllText(Path.Combine(setup,"defaults.json"),"{\"Url\":\"https://default.test\",\"SaveSeconds\":90,\"AllowHttp\":true}");
   w.LoadDefaults(setup);Check(w.settings.Url=="https://default.test"&&w.settings.SaveSeconds==90&&w.NewDefaultAccount().AllowHttp,"Initial defaults file loading");
   w.settings=SettingsLayers.Load(w.defaultsJson,"{\"SaveSeconds\":30,\"Accounts\":[{\"Name\":\"saved\"}]}");Check(w.settings.SaveSeconds==30&&w.settings.Accounts[0].Url=="https://default.test","Missing account setting did not inherit default");
   File.WriteAllText(Path.Combine(setup,"settings.policy.json"),"{\"UpdateFolder\":\"legacy-folder\"}");File.WriteAllText(Path.Combine(setup,"settings.override.json"),"{\"Url\":\"https://forced.test\",\"ActivityGroupingPattern\":\"(.*):(.*)\",\"UpdateFolder\":\"forced-folder\"}");w.ApplyStartupOverrides(setup);w.settings.Url="https://changed.test";w.settings.Accounts[0].Url="https://changed.test";w.StoreSettings();Check(w.settings.Url=="https://forced.test"&&w.settings.Accounts[0].Url=="https://forced.test"&&w.settings.UpdateFolder=="forced-folder"&&w.NewDefaultAccount().Url=="https://forced.test","Override priority after account switch/save");
   IEnumerable<DependencyObject> Descendants(DependencyObject node){for(int i=0;i<VisualTreeHelper.GetChildrenCount(node);i++){var child=VisualTreeHelper.GetChild(node,i);yield return child;foreach(var inner in Descendants(child))yield return inner;}}
   void Capture(Window dialog,string name){dialog.UpdateLayout();var bitmap=new RenderTargetBitmap((int)dialog.ActualWidth,(int)dialog.ActualHeight,96,96,PixelFormats.Pbgra32);bitmap.Render(dialog);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bitmap));using var file=File.Create(Path.Combine(AppContext.BaseDirectory,name));encoder.Save(file);}
   void Dialog(Action show,Func<Window,Task> test){Exception error=null;w.Dispatcher.BeginInvoke(DispatcherPriority.ContextIdle,new Action(async()=>{var dialog=w.OwnedWindows.Cast<Window>().Single();try{dialog.UpdateLayout();await test(dialog);}catch(Exception ex){error=ex;}finally{dialog.Close();}}));show();if(error!=null)throw error;}
   Dialog(()=>w.EditAccount(w,w.NewDefaultAccount()),dialog=>{var url=Descendants(dialog).OfType<TextBox>().Single(b=>b.Text=="https://forced.test");Check(!url.IsEnabled,"Overridden URL not greyed out");Capture(dialog,"managed-account-preview.png");return Task.CompletedTask;});
   Dialog(w.ViewSettingsDialog,dialog=>{var pattern=Descendants(dialog).OfType<TextBox>().Single(b=>b.Text=="(.*):(.*)");Check(!pattern.IsEnabled,"Overridden regex not greyed out");return Task.CompletedTask;});
   w.managedSettings=new ManagedSettings();w.settings=new ConnectionSettings {ExcludedReportUserIds=new List<int>{8}};
   w.settings.Accounts.Add(new AccountProfile {Name="unrelated legacy account",ProtectedToken="unreadable-legacy-token"});
   Dialog(()=>w.ReportSettingsDialog(w),dialog=>{var boxes=Descendants(dialog).OfType<TextBox>().ToList();boxes[0].Text="８、９\t１０";boxes[1].Text="７.５";Descendants(dialog).OfType<Button>().Single(b=>b.Content as string=="保存").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(!dialog.IsVisible&&w.settings.ReportMinimumHours==7.5m&&w.settings.ExcludedReportUserIds.SequenceEqual(new[]{8,9,10}),"Report settings save failed or migrated unrelated credentials");return Task.CompletedTask;});
   w.settings.Accounts.Clear();w.settings.ExcludedReportUserIds=new List<int>{8};
   w.service=new KimaiService("https://example.test","test-token","",false,new ReportMock());await w.service.InitializeAsync(false);w.service.Projects.AddRange(new[]{new ProjectCollection {Id=11,Name="制作案件",Visible=true},new ProjectCollection {Id=12,Name="運用案件",Visible=true}});w.service.Activities.AddRange(new[]{new ActivityCollection {Id=21,Project=11,Name="設計",Visible=true},new ActivityCollection {Id=22,Project=12,Name="レビュー",Visible=true}});Projects=w.service.Projects.Select(p=>w.service.ProjectName(p.Id.Value)).ToArray();
   Dialog(w.ShowServerReports,async dialog=>{var dates=Descendants(dialog).OfType<DatePicker>().ToList();Check(dates[0].SelectedDate==Monday(DateTime.Today),"Report default is not this week");dates[0].SelectedDate=new DateTime(2026,9,21);dates[1].SelectedDate=new DateTime(2026,9,27);Descendants(dialog).OfType<Button>().Single(b=>b.Content as string=="取得して集計").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await WaitUntil(()=>Descendants(dialog).OfType<TabControl>().Any(t=>t.Items.Count>=10));var tabs=Descendants(dialog).OfType<TabControl>().Single();var daily=(DataTable)((TabItem)tabs.Items[0]).Tag;Check(daily.Rows.Count==2&&(decimal)daily.Rows.Cast<DataRow>().Single(r=>r[0].ToString().Contains("self"))[1]==.5m,"Daily report UI exclusion or duration");dialog.UpdateLayout();var grid=(DataGrid)((TabItem)tabs.Items[0]).Content;Check(grid.Columns[1].Width.Value==30&&grid.Columns[1].CellStyle!=null,"Below-threshold highlighting absent");Capture(dialog,"daily-report-preview.png");tabs.SelectedIndex=tabs.Items.Count-1;var details=(DataTable)((TabItem)tabs.Items[tabs.Items.Count-1]).Tag;Check(details.Rows.Count==1&&details.Columns.Contains("作業時間(分)"),"Project detail UI");Capture(dialog,"project-report-preview.png");Descendants(dialog).OfType<Button>().Single(b=>b.Content as string=="翌月 ▶").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await WaitUntil(()=>tabs.Items.Count>=10);Check(dates[0].SelectedDate==new DateTime(2026,10,1)&&dates[1].SelectedDate==new DateTime(2026,10,31),"Next month navigation dates");dialog.UpdateLayout();var month=(DataGrid)((TabItem)tabs.Items[0]).Content;Check(month.Columns.Count==33&&month.Columns[1].ActualWidth<=30,"Monthly matrix is not compact");Capture(dialog,"daily-month-preview.png");Descendants(dialog).OfType<Button>().Single(b=>b.Content as string=="◀ 前月").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await WaitUntil(()=>tabs.Items.Count>=10);Check(dates[0].SelectedDate==new DateTime(2026,9,1)&&dates[1].SelectedDate==new DateTime(2026,9,30),"Previous month navigation dates");});
   w.settings.PeriodReport=new PeriodReportConfig {ServerUrl=w.service.BaseUrl,Rows=new List<ProjectPeriodSpec>{new ProjectPeriodSpec {ProjectId=11,ProjectName=Projects[0],Header="第1期間",From=new DateTime(2026,9,21),Through=new DateTime(2026,9,21)},new ProjectPeriodSpec {ProjectId=11,ProjectName=Projects[0],Header="第2期間",From=new DateTime(2026,9,22),Through=new DateTime(2026,9,23)},new ProjectPeriodSpec {ProjectId=12,ProjectName=Projects[1],Header="第1期間",From=new DateTime(2026,9,22),Through=new DateTime(2026,9,23)}}};
   Dialog(()=>w.ShowPeriodReports(w),async dialog=>{Descendants(dialog).OfType<Button>().Single(b=>b.Content as string=="取得して集計").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));await WaitUntil(()=>Descendants(dialog).OfType<TabControl>().Any());var tabs=Descendants(dialog).OfType<TabControl>().Single();var grid=(DataGrid)((TabItem)tabs.Items[0]).Content;Check(((DataView)grid.ItemsSource).Table.Rows.Count==2,"Period report UI totals rows");Capture(dialog,"period-report-preview.png");var matrix=Descendants(dialog).OfType<DataGrid>().Single(g=>g.FrozenColumnCount==1&&g.SelectionUnit==DataGridSelectionUnit.Cell);Check(matrix.Items.Count==2&&matrix.Columns.Count==3,"Period editor is not project-by-header matrix");var periodNames=Descendants(dialog).OfType<ComboBox>().Single(c=>c.ItemsSource is string[]&&c.Items.Contains("第1期間"));Check(periodNames.IsEditable&&periodNames.Items.Contains("第2期間"),"Existing period names missing from dropdown");periodNames.SelectedItem="第2期間";Check(periodNames.Text=="第2期間","Period dropdown selection did not update text");dialog.UpdateLayout();foreach(var column in matrix.Columns){var columnHeader=Descendants(matrix).OfType<System.Windows.Controls.Primitives.DataGridColumnHeader>().Single(h=>h.Column==column);var click=typeof(System.Windows.Controls.Primitives.DataGridColumnHeader).GetMethod("OnClick",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);for(int repeat=0;repeat<2;repeat++){click.Invoke(columnHeader,null);dialog.UpdateLayout();Check(matrix.Items.SortDescriptions.Count>0&&matrix.Items.SortDescriptions[0].PropertyName==column.SortMemberPath,"Matrix header sort member invalid");var sortedRow=(DataRowView)matrix.Items[0];matrix.SelectedCells.Clear();matrix.SelectedCells.Add(new DataGridCellInfo(sortedRow,matrix.Columns[1]));Check(Descendants(dialog).OfType<ProjectSearchBox>().Single().SelectedItem as string==w.service.ProjectName((int)sortedRow["ProjectId"]),"Sorting selected another project");}}matrix.SelectedCells.Clear();var firstProject=matrix.Items.Cast<DataRowView>().Single(r=>(int)r["ProjectId"]==11);matrix.SelectedCells.Add(new DataGridCellInfo(firstProject,matrix.Columns[1]));foreach(var checkbox in Descendants(dialog).OfType<CheckBox>().Where(c=>(c.Content as string)=="開始からすべて"||(c.Content as string)=="以降すべて"))checkbox.IsChecked=true;Descendants(dialog).OfType<Button>().Single(b=>b.Content as string=="選択期間を更新").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Descendants(dialog).OfType<ComboBox>().Single(t=>t.ItemsSource is string[]&&t.Items.Contains("第1期間")).Text="累計期間";Descendants(dialog).OfType<Button>().Single(b=>b.Content as string=="期間名を変更").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Check(matrix.Columns[1].Header as string=="累計期間","Matrix header rename failed");});
   var stored=SettingsLayers.Load(null,File.ReadAllText(w.testSettingsPath));Check(stored.PeriodReport.Rows.Count==3&&stored.PeriodReport.Rows.Count(r=>r.Header=="累計期間")==2&&!stored.PeriodReport.Rows[0].From.HasValue&&!stored.PeriodReport.Rows[0].Through.HasValue,"Open range or header rename not persisted");
   Console.WriteLine("PASS: actual defaults/override files, account defaults, greyed fields, user-filtered daily/project report UI, threshold styles and persistent period report UI.");
  }finally{w.closingApproved=true;w.Close();}
 }
}
